/**
 * Database Type Definitions for D&D 5e DM Tool
 * 
 * This file contains all TypeScript interfaces for the data models used in the app.
 * These interfaces define the shape of data stored in IndexedDB via Dexie.js.
 * 
 * Key concepts:
 * - id?: number - Optional ID (auto-generated by Dexie when inserted)
 * - campaign_id: number - Foreign key linking to a campaign
 * - Timestamps use Unix timestamps (milliseconds since epoch)
 * - All optional fields use ? to indicate they can be undefined
 */

/**
 * Campaign - Top-level organizational unit
 * 
 * Campaigns group related characters, monsters, encounters, and sessions.
 * A DM can have multiple campaigns and switch between them.
 */
export interface Campaign {
  id?: number; // Auto-generated primary key
  name: string; // Campaign name (e.g., "Lost Mine of Phandelver")
  settings?: {
    notes?: string; // Optional campaign-wide notes
    [key: string]: unknown; // Extensible for future settings
  };
  created_at: number; // Unix timestamp of creation
  updated_at: number; // Unix timestamp of last update
}

/**
 * D&D 5e Ability Scores
 * Standard six ability scores (3-20+ range typically)
 */
export interface AbilityScores {
  str: number; // Strength
  dex: number; // Dexterity
  con: number; // Constitution
  int: number; // Intelligence
  wis: number; // Wisdom
  cha: number; // Charisma
}

export interface SavingThrows {
  str?: boolean;
  dex?: boolean;
  con?: boolean;
  int?: boolean;
  wis?: boolean;
  cha?: boolean;
}

export interface Skill {
  name: string;
  ability: keyof AbilityScores;
  proficient?: boolean;
  expertise?: boolean;
}

export interface Action {
  name: string;
  description: string;
  type?: "melee" | "ranged" | "spell" | "other";
  attack_bonus?: number;
  damage?: string;
  range?: string;
}

export interface Spell {
  name: string;
  level: number;
  school?: string;
  casting_time?: string;
  range?: string;
  components?: string;
  duration?: string;
  description?: string;
}

/**
 * Player Character
 * 
 * Stores player character information for DM reference.
 * Can be used in combat tracker by linking via reference_id.
 */
export interface Character {
  id?: number; // Auto-generated primary key
  campaign_id: number; // Which campaign this character belongs to
  name: string; // Character name
  class?: string; // Character class (e.g., "Fighter", "Wizard")
  level?: number; // Character level (1-20)
  hp: number; // Current hit points
  max_hp: number; // Maximum hit points
  temp_hp?: number; // Temporary hit points
  ac: number; // Armor class
  stats: AbilityScores; // Ability scores (STR, DEX, CON, INT, WIS, CHA)
  saving_throws?: SavingThrows; // Proficient saving throws
  skills?: Skill[]; // Skill proficiencies
  spells?: Spell[]; // Known/prepared spells
  notes?: string; // DM notes about the character
  created_at: number; // Unix timestamp
  updated_at: number; // Unix timestamp
}

/**
 * Monster Stat Block
 * 
 * Stores full monster/creature stat blocks. Can be manually entered,
 * imported from Open5e API (SRD only), or created as homebrew.
 * Used as templates for adding combatants to encounters/combat.
 */
export interface Monster {
  id?: number; // Auto-generated primary key
  campaign_id: number; // Which campaign this monster belongs to
  name: string; // Monster name (e.g., "Goblin", "Ancient Red Dragon")
  cr?: number | string; // Challenge Rating: "1/8", "1/4", "1/2", or numbers 1-30
  size?: string; // Tiny, Small, Medium, Large, Huge, Gargantuan
  type?: string; // Beast, Humanoid, Dragon, Undead, etc.
  alignment?: string; // Lawful Good, Neutral Evil, etc.
  hp: number; // Current hit points (for templates, usually = max_hp)
  max_hp: number; // Maximum hit points
  ac: number; // Armor class
  speed?: string; // Movement speeds (e.g., "30 ft., fly 60 ft.")
  stats: AbilityScores; // Ability scores
  saving_throws?: SavingThrows; // Proficient saving throws
  skills?: Skill[]; // Skill proficiencies
  damage_resistances?: string[]; // e.g., ["fire", "bludgeoning from nonmagical attacks"]
  damage_immunities?: string[]; // e.g., ["poison", "psychic"]
  condition_immunities?: string[]; // e.g., ["charmed", "frightened"]
  senses?: string; // e.g., "darkvision 60 ft., passive Perception 12"
  languages?: string; // e.g., "Common, Draconic"
  actions?: Action[]; // Standard actions (attacks, abilities)
  legendary_actions?: Action[]; // Legendary actions (for CR 5+ creatures)
  source?: "srd" | "homebrew" | "manual"; // Where this monster came from
  open5e_id?: string; // Unique ID from Open5e API (if imported)
  notes?: string; // DM notes about this monster
  created_at: number; // Unix timestamp
  updated_at: number; // Unix timestamp
}

export interface NPC {
  id?: number;
  campaign_id: number;
  name: string;
  role?: string;
  location?: string;
  notes?: string;
  created_at: number;
  updated_at: number;
}

export interface CombatantTemplate {
  id: string; // Temporary ID for template
  type: "monster" | "character" | "npc" | "custom";
  reference_id?: number; // ID of monster/character if applicable
  name: string;
  hp: number;
  max_hp: number;
  ac: number;
  initiative?: number;
}

export interface Encounter {
  id?: number;
  campaign_id: number;
  name: string;
  combatants: CombatantTemplate[];
  difficulty?: "easy" | "medium" | "hard" | "deadly";
  notes?: string;
  created_at: number;
  updated_at: number;
}

export interface Condition {
  name: string;
  description?: string;
  duration?: string; // e.g., "1 round", "until removed"
}

/**
 * Combatant - Active participant in combat
 * 
 * Represents a single entity in active combat. This is a runtime instance
 * that may reference a Monster, Character, or NPC, or be a custom combatant.
 * HP and conditions are tracked per-combatant and don't affect the template.
 */
export interface Combatant {
  id: string; // Unique ID for this combat instance (e.g., "monster-1234567890")
  type: "monster" | "character" | "npc" | "custom"; // What type of combatant
  reference_id?: number; // ID of the original monster/character/NPC (if applicable)
  name: string; // Display name in combat (e.g., "Goblin 1", "Goblin 2")
  hp: number; // Current hit points (changes during combat)
  max_hp: number; // Maximum hit points
  temp_hp?: number; // Temporary hit points (absorb damage first)
  ac: number; // Armor class
  initiative: number; // Initiative roll (determines turn order)
  conditions: Condition[]; // Active conditions (poisoned, stunned, etc.)
  notes?: string; // Combat-specific notes
}

/**
 * Active Combat Session
 * 
 * Represents an ongoing combat encounter. Only one active combat
 * per campaign at a time. Stores all combatants, turn order, and round tracking.
 * This persists across page reloads so you never lose combat state!
 */
export interface ActiveCombat {
  id?: number; // Auto-generated primary key (one per campaign)
  campaign_id: number; // Which campaign this combat belongs to
  combatants: Combatant[]; // All participants (sorted by initiative)
  round: number; // Current round number (starts at 1)
  current_turn_index: number; // Index in combatants array (whose turn it is)
  started_at: number; // Unix timestamp when combat began
  updated_at: number; // Unix timestamp of last update
}

/**
 * Session Notes
 * 
 * Records what happened during a game session. Used for campaign
 * timeline and recaps. Helps DMs remember what happened last time!
 */
export interface Session {
  id?: number; // Auto-generated primary key
  campaign_id: number; // Which campaign this session belongs to
  date: number; // Unix timestamp of when session occurred
  recap?: string; // Summary of what happened
  notes?: string; // Detailed notes, NPCs met, plot developments, etc.
  created_at: number; // Unix timestamp
  updated_at: number; // Unix timestamp
}

/**
 * Database Export Format
 * 
 * Structure for JSON export/import. Used for backup and transferring
 * data between browsers/computers. Includes version for future migrations.
 * Note: active_combat is NOT exported (only save encounters, not in-progress battles)
 */
export interface DatabaseExport {
  version: string; // Export format version (for future compatibility)
  exported_at: number; // Unix timestamp of when export was created
  campaigns: Campaign[]; // All campaigns
  characters: Character[]; // All characters
  monsters: Monster[]; // All monsters
  npcs: NPC[]; // All NPCs
  encounters: Encounter[]; // All saved encounters
  sessions: Session[]; // All session notes
}
